[package]
name = "padu-daemon"
version = "0.1.2"
edition = "2024"
description = "Headless Padu provider daemon"
license = "GPL-3.0-only"
readme = "README.md"

[features]
dev-binary = []

[[bin]]
name = "padu-daemon"
path = "src/main.rs"

[[bin]]
name = "padu-debug-daemon"
path = "src/bin/padu-debug-daemon.rs"
required-features = ["dev-binary"]

[[bin]]
name = "padu-provider-test"
path = "src/bin/provider_test.rs"

[dependencies]
anyhow = "1.0"
crossbeam-channel = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smol = "2"
padu-core = { path = "../padu-core" }
padu-protocol = { path = "../padu-protocol" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
] }
