//! Rich markdown rendering: LaTeX → SVG (MathJax) produced by a dedicated
//! QuickJS worker isolate, and Mermaid → SVG produced natively by
//! `padu-mermaid` (merman + theme postprocessing) — both cached on disk and
//! in memory, and handed to GPUI as SVG [`Image`]s that its own asset system
//! rasterizes and repaints asynchronously.
//!
//! Ownership of the isolate stays on a single background thread, so the GPUI
//! render thread never runs JS: a render pass only locks the in-memory cache
//! (a hash lookup) and enqueues a request when the block is unknown. The worker
//! resolves requests serially, checks the disk cache first, renders through
//! the JS bundle (math) or the native renderer (mermaid) when it must,
//! persists the SVG, and marks the entry ready — which the image source loader
//! observes on its next poll and repaints.
//!
//! The math JS bundle lives in `rich/js/` and is regenerated by
//! `scripts/build-rich-render.ts`; it is committed so the crate compiles
//! offline. KaTeX is the web client's math engine but only emits HTML/CSS,
//! never SVG, so the desktop isolate uses MathJax v3's SVG output jax with the
//! same `$…$`/`$$…$$` surface and macro set. Mermaid needs no bundle: it
//! renders headless in pure Rust with a vendored text measurer, so diagrams
//! never depend on a DOM shim.

use std::collections::{HashMap, VecDeque};
use std::path::PathBuf;
use std::sync::{Arc, OnceLock};
use std::time::{Duration, Instant, SystemTime};

use crossbeam_channel::{Receiver, Sender};
use gpui::{App, Image, ImageCacheError, ImageFormat, ImageSource, RenderImage, Window};
use parking_lot::Mutex;
use rquickjs::{Context, Function, Runtime, Value};
use serde::Serialize;

const MATH_BUNDLE: &str = include_str!("rich/js/math.bundle.js");

const CACHE_DIR_NAME: &str = "render-cache";
/// Disk cache cap for `~/.padu/render-cache/`. Eviction removes the oldest
/// files by modified time until the directory sits under the cap again.
const DISK_CAP_BYTES: u64 = 64 * 1024 * 1024;
/// In-memory entry cap, approximate LRU by insertion order.
const MEMORY_CAP_ENTRIES: usize = 256;
/// Upper bound for a single JS render before the worker reports a timeout.
const RENDER_DEADLINE: Duration = Duration::from_secs(30);
/// Cadence at which a pending image source re-checks the cache.
const WAIT_POLL: Duration = Duration::from_millis(50);

/// What kind of rich content a render request carries.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RichKind {
    Math { display: bool },
    Mermaid,
}

impl RichKind {
    fn tag(self) -> &'static str {
        match self {
            RichKind::Math { display: true } => "math-display",
            RichKind::Math { display: false } => "math-inline",
            // The native renderer (padu-mermaid) replaced the QuickJS one, and
            // QuickJS-era SVGs rasterize blank under resvg — yet the disk
            // cache outlives the renderer that wrote it. A new tag guarantees
            // those stale entries are never served again; they age out through
            // the disk-cap eviction. Bump the version whenever the native
            // theme mapping changes its output for the same source (canvas,
            // fills, padding, fonts).
            RichKind::Mermaid => "mermaid-native-v3",
        }
    }
}

/// Theme colors for a rich render, serialized straight to the JS call. Every
/// value participates in the cache key so a theme switch re-renders rather
/// than reusing an SVG painted for the other appearance.
#[derive(Clone, Debug, Serialize)]
pub struct RenderTheme {
    pub is_dark: bool,
    pub font_px: f32,
    pub text: String,
    pub secondary: String,
    pub tertiary: String,
    pub border: String,
    pub card: String,
    pub surface: String,
    pub accent: String,
    pub success: String,
    pub warning: String,
    pub danger: String,
    pub font_family: String,
}

impl RenderTheme {
    pub fn signature(&self) -> String {
        let font_px = self.font_px.to_string();
        [
            if self.is_dark { "d" } else { "l" },
            font_px.as_str(),
            self.text.as_str(),
            self.secondary.as_str(),
            self.tertiary.as_str(),
            self.border.as_str(),
            self.card.as_str(),
            self.surface.as_str(),
            self.accent.as_str(),
            self.success.as_str(),
            self.warning.as_str(),
            self.danger.as_str(),
            self.font_family.as_str(),
        ]
        .join("|")
    }

    pub fn to_json(&self) -> String {
        serde_json::to_string(self).unwrap_or_else(|_| "{}".into())
    }
}

/// Content-addressed key for a rich block: kind + source + theme colors.
pub fn hash(kind: RichKind, source: &str, theme: &RenderTheme) -> u64 {
    let mut hasher = blake3::Hasher::new();
    hasher.update(kind.tag().as_bytes());
    hasher.update(&[0]);
    hasher.update(source.as_bytes());
    hasher.update(&[0]);
    hasher.update(theme.signature().as_bytes());
    let out = hasher.finalize();
    u64::from_le_bytes(
        out.as_bytes()[..8]
            .try_into()
            .expect("blake3 output is 32 bytes"),
    )
}

// ── Cache ──────────────────────────────────────────────────────────────────

enum Entry {
    Ready { image: Arc<Image> },
    Error { message: String },
    InFlight,
}

struct CacheInner {
    entries: HashMap<u64, Entry>,
    order: VecDeque<u64>,
}

struct DiskCache {
    dir: PathBuf,
}

impl DiskCache {
    fn new() -> Self {
        let dir = crate::projectless::home_directory()
            .or_else(|| dirs::home_dir().map(|home| home.join(".padu")))
            .map(|home| home.join(CACHE_DIR_NAME))
            .unwrap_or_else(|| std::env::temp_dir().join("padu-render-cache"));
        Self { dir }
    }

    fn path(&self, hash: u64) -> PathBuf {
        self.dir.join(format!("{hash:016x}.svg"))
    }

    fn load(&self, hash: u64) -> Option<String> {
        std::fs::read_to_string(self.path(hash)).ok()
    }

    fn save(&self, hash: u64, svg: &str) {
        if std::fs::create_dir_all(&self.dir).is_err() {
            return;
        }
        let _ = std::fs::write(self.path(hash), svg);
        self.enforce_cap();
    }

    /// Evict the oldest files until the directory total is under the cap.
    fn enforce_cap(&self) {
        let mut files: Vec<(SystemTime, PathBuf)> = match std::fs::read_dir(&self.dir) {
            Ok(entries) => entries
                .filter_map(|entry| {
                    let entry = entry.ok()?;
                    if entry.file_type().ok()?.is_file() {
                        let modified = entry.metadata().ok()?.modified().ok()?;
                        Some((modified, entry.path()))
                    } else {
                        None
                    }
                })
                .collect(),
            Err(_) => return,
        };
        let total: u64 = files
            .iter()
            .map(|(_, path)| path.metadata().map(|meta| meta.len()).unwrap_or(0))
            .sum();
        if total <= DISK_CAP_BYTES {
            return;
        }
        files.sort();
        let mut removed = 0u64;
        for (_, path) in files {
            if total - removed <= DISK_CAP_BYTES {
                break;
            }
            if let Ok(size) = path.metadata().map(|meta| meta.len()) {
                if std::fs::remove_file(&path).is_ok() {
                    removed += size;
                }
            }
        }
    }
}

pub struct RichCache {
    inner: Mutex<CacheInner>,
    disk: DiskCache,
}

impl RichCache {
    fn new() -> Self {
        Self {
            inner: Mutex::new(CacheInner {
                entries: HashMap::new(),
                order: VecDeque::new(),
            }),
            disk: DiskCache::new(),
        }
    }

    /// True once the entry has settled into a ready image or an error; an
    /// in-flight marker is not enough for a waiter to stop polling.
    fn settled(&self, hash: u64) -> bool {
        matches!(
            self.inner.lock().entries.get(&hash),
            Some(Entry::Ready { .. } | Entry::Error { .. })
        )
    }
}

/// What the image source loader should paint while the cache resolves.
#[derive(Debug)]
pub enum RenderOutcome {
    Ready(Arc<Image>),
    Error(String),
    Pending,
}

/// A request queued to the worker thread.
pub struct WorkerRequest {
    pub hash: u64,
    pub kind: RichKind,
    pub source: String,
    pub theme: RenderTheme,
    /// Native Mermaid theme, present only for [`RichKind::Mermaid`]. Carried
    /// alongside (rather than re-derived from hex) so the worker sees the full
    /// palette fidelity without a lossy hex round-trip.
    pub mermaid_theme: Option<padu_mermaid::MermaidTheme>,
}

pub struct RichRenderer {
    cache: Arc<RichCache>,
    worker: Sender<WorkerRequest>,
}

static RICH: OnceLock<Arc<RichRenderer>> = OnceLock::new();

impl RichRenderer {
    fn spawn() -> Arc<Self> {
        let cache = Arc::new(RichCache::new());
        let (sender, receiver) = crossbeam_channel::unbounded::<WorkerRequest>();
        let worker_cache = cache.clone();
        std::thread::Builder::new()
            .name("padu-rich-render".into())
            .spawn(move || worker_loop(receiver, worker_cache))
            .expect("could not spawn the rich-render worker");
        Arc::new(Self {
            cache,
            worker: sender,
        })
    }

    fn ensure(
        &self,
        hash: u64,
        kind: RichKind,
        source: String,
        theme: RenderTheme,
        mermaid_theme: Option<padu_mermaid::MermaidTheme>,
    ) -> RenderOutcome {
        {
            let mut inner = self.cache.inner.lock();
            match inner.entries.get(&hash) {
                Some(Entry::Ready { image }) => return RenderOutcome::Ready(image.clone()),
                Some(Entry::Error { message }) => return RenderOutcome::Error(message.clone()),
                Some(Entry::InFlight) => return RenderOutcome::Pending,
                None => {}
            }
            inner.entries.insert(hash, Entry::InFlight);
            inner.order.push_back(hash);
            while inner.entries.len() > MEMORY_CAP_ENTRIES {
                let Some(old) = inner.order.pop_front() else {
                    break;
                };
                if old != hash {
                    inner.entries.remove(&old);
                }
            }
        }
        let _ = self.worker.send(WorkerRequest {
            hash,
            kind,
            source,
            theme,
            mermaid_theme,
        });
        RenderOutcome::Pending
    }

    fn settled(&self, hash: u64) -> bool {
        self.cache.settled(hash)
    }
}

impl RichCache {
    fn complete(&self, hash: u64, result: Result<String, String>) {
        {
            let mut inner = self.inner.lock();
            let Some(previous) = inner.entries.remove(&hash) else {
                return;
            };
            if !matches!(previous, Entry::InFlight) {
                return;
            }
            let entry = match result {
                Ok(svg) => Entry::Ready {
                    image: Arc::new(Image::from_bytes(ImageFormat::Svg, svg.into_bytes())),
                },
                Err(message) => Entry::Error { message },
            };
            inner.entries.insert(hash, entry);
            inner.order.push_back(hash);
        }
        // The loader's poll loop observes the ready entry and repaints; no
        // cross-thread wake is needed.
    }
}

/// Build the `ImageSource` for a rich block. The loader resolves from the
/// cache each layout pass: ready SVG is rasterized by GPUI's asset system,
/// errors surface through `with_fallback`, and a pending block enqueues the
/// render (once) and schedules a repaint when it lands.
pub fn rich_image_source(
    hash: u64,
    kind: RichKind,
    source: String,
    theme: RenderTheme,
) -> impl Fn(&mut Window, &mut App) -> Option<Result<Arc<RenderImage>, ImageCacheError>> + 'static {
    let cache: Arc<RichRenderer> = RICH.get_or_init(RichRenderer::spawn).clone();
    move |window, cx| match cache.ensure(hash, kind, source.clone(), theme.clone(), None) {
        RenderOutcome::Ready(image) => image.use_render_image(window, cx).map(Ok),
        RenderOutcome::Error(message) => Some(Err(ImageCacheError::Other(Arc::new(
            anyhow::anyhow!(message),
        )))),
        RenderOutcome::Pending => {
            let wait_cache = cache.clone();
            window
                .spawn(cx, async move |cx| {
                    let deadline = Instant::now() + RENDER_DEADLINE;
                    while Instant::now() < deadline {
                        if wait_cache.settled(hash) {
                            break;
                        }
                        cx.background_executor().timer(WAIT_POLL).await;
                    }
                    cx.refresh();
                })
                .detach();
            None
        }
    }
}

/// The `ImageSource` value for a rich block, ready for `img(...)`.
pub fn rich_image_source_value(
    hash: u64,
    kind: RichKind,
    source: String,
    theme: RenderTheme,
) -> ImageSource {
    ImageSource::Custom(Arc::new(rich_image_source(hash, kind, source, theme)))
}

/// Build the `ImageSource` for a Mermaid diagram. Same contract as
/// [`rich_image_source`], but the worker renders natively through
/// `padu-mermaid` instead of the QuickJS isolate.
pub fn mermaid_image_source(
    hash: u64,
    source: String,
    theme: RenderTheme,
    mermaid_theme: padu_mermaid::MermaidTheme,
) -> impl Fn(&mut Window, &mut App) -> Option<Result<Arc<RenderImage>, ImageCacheError>> + 'static {
    let cache: Arc<RichRenderer> = RICH.get_or_init(RichRenderer::spawn).clone();
    move |window, cx| match cache.ensure(
        hash,
        RichKind::Mermaid,
        source.clone(),
        theme.clone(),
        Some(mermaid_theme.clone()),
    ) {
        RenderOutcome::Ready(image) => image.use_render_image(window, cx).map(Ok),
        RenderOutcome::Error(message) => Some(Err(ImageCacheError::Other(Arc::new(
            anyhow::anyhow!(message),
        )))),
        RenderOutcome::Pending => {
            let wait_cache = cache.clone();
            window
                .spawn(cx, async move |cx| {
                    let deadline = Instant::now() + RENDER_DEADLINE;
                    while Instant::now() < deadline {
                        if wait_cache.settled(hash) {
                            break;
                        }
                        cx.background_executor().timer(WAIT_POLL).await;
                    }
                    cx.refresh();
                })
                .detach();
            None
        }
    }
}

/// The `ImageSource` value for a Mermaid diagram, ready for `img(...)`.
pub fn mermaid_image_source_value(
    hash: u64,
    source: String,
    theme: RenderTheme,
    mermaid_theme: padu_mermaid::MermaidTheme,
) -> ImageSource {
    ImageSource::Custom(Arc::new(mermaid_image_source(
        hash,
        source,
        theme,
        mermaid_theme,
    )))
}

// ── Worker ─────────────────────────────────────────────────────────────────

fn worker_loop(receiver: Receiver<WorkerRequest>, cache: Arc<RichCache>) {
    let mut isolate: Option<Result<RichIsolate, String>> = None;
    while let Ok(request) = receiver.recv() {
        let result = match cache.disk.load(request.hash) {
            Some(svg) => Ok(svg),
            None => {
                let rendered = match request.kind {
                    // Native headless render: no isolate needed, and a broken
                    // isolate must not fail diagrams.
                    RichKind::Mermaid => {
                        let theme = request.mermaid_theme.unwrap_or_default();
                        padu_mermaid::render_to_svg(&request.source, &theme)
                            .map_err(|error| error.to_string())
                    }
                    RichKind::Math { .. } => match &mut isolate {
                        Some(Err(message)) => Err(message.clone()),
                        Some(Ok(iso)) => iso.render(&request),
                        None => {
                            let built = RichIsolate::new().map_err(|error| error.to_string());
                            let rendered = match &built {
                                Ok(iso) => iso.render(&request),
                                Err(message) => Err(message.clone()),
                            };
                            isolate = Some(built);
                            rendered
                        }
                    },
                };
                if let Ok(svg) = &rendered {
                    cache.disk.save(request.hash, svg);
                }
                rendered
            }
        };
        cache.complete(request.hash, result);
    }
}

/// The QuickJS isolate. Owned exclusively by the worker thread, so it is not
/// `Send`; the renderer never touches it from the GPUI thread.
struct RichIsolate {
    context: Context,
    _runtime: Runtime,
}

impl RichIsolate {
    fn new() -> anyhow::Result<Self> {
        use anyhow::Context as _;
        let runtime = Runtime::new().context("could not create the QuickJS runtime")?;
        runtime.set_memory_limit(512 * 1024 * 1024);
        runtime.set_max_stack_size(8 * 1024 * 1024);
        let context = Context::full(&runtime).context("could not create the QuickJS context")?;
        context
            .with(|ctx| -> Result<(), String> {
                // QuickJS has no `console` or timers; libraries use both defensively.
                // `setTimeout` defers work some diagram paths rely on, so the
                // stub runs the callback immediately rather than dropping it.
                ctx.eval::<(), _>(
                    "globalThis.console = { log(){}, warn(){}, error(){}, info(){}, debug(){}, trace(){} };\
                     globalThis.setTimeout = function (fn) { if (typeof fn === 'function') { fn(); } return 0; };\
                     globalThis.clearTimeout = function () {};\
                     globalThis.setInterval = function () { return 0; };\
                     globalThis.clearInterval = function () {};",
                )
                .map_err(|error| quickjs_message(&ctx, &error))?;
                ctx.eval::<(), _>(MATH_BUNDLE)
                    .map_err(|error| quickjs_message(&ctx, &error))?;
                Ok(())
            })
            .map_err(|message| anyhow::anyhow!("{message}"))
            .context("could not initialize the rich-render isolate")?;
        Ok(Self {
            context,
            _runtime: runtime,
        })
    }

    fn render(&self, request: &WorkerRequest) -> Result<String, String> {
        match request.kind {
            RichKind::Math { display } => {
                self.render_math(&request.source, display, &request.theme)
            }
            // Mermaid renders natively in `worker_loop` and never reaches the
            // isolate; reaching here means a request was built without a theme.
            RichKind::Mermaid => Err("diagram render reached the math isolate".into()),
        }
    }

    fn render_math(
        &self,
        source: &str,
        display: bool,
        theme: &RenderTheme,
    ) -> Result<String, String> {
        self.context.with(|ctx| {
            let globals = ctx.globals();
            let render: Function<'_> = globals
                .get("__paduRenderMath")
                .map_err(|error| quickjs_message(&ctx, &error))?;
            let theme_json = theme.to_json();
            let result: Value<'_> = render
                .call((source, display, theme_json))
                .map_err(|error| quickjs_message(&ctx, &error))?;
            let object = result
                .into_object()
                .ok_or_else(|| "math render returned a non-object".to_string())?;
            if let Ok(svg) = object.get::<_, String>("svg") {
                Ok(svg)
            } else {
                let message: String = object
                    .get("error")
                    .unwrap_or_else(|_| "math render failed".into());
                Err(message)
            }
        })
    }
}

fn quickjs_message(ctx: &rquickjs::Ctx<'_>, error: &rquickjs::Error) -> String {
    if matches!(error, rquickjs::Error::Exception) {
        let caught = ctx.catch();
        if let Ok(exception) = rquickjs::Exception::from_value(caught.clone()) {
            return exception
                .message()
                .or_else(|| exception.stack())
                .unwrap_or_else(|| "JavaScript execution failed".into());
        }
        if let Some(string) = caught
            .as_string()
            .and_then(|string| string.to_string().ok())
        {
            return string;
        }
    }
    error.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn theme() -> RenderTheme {
        RenderTheme {
            is_dark: true,
            font_px: 14.0,
            text: "#e2e2e2".into(),
            secondary: "#a3a3a3".into(),
            tertiary: "#7d7d7d".into(),
            border: "#2c2c2c".into(),
            card: "#212121".into(),
            surface: "#1a1a1a".into(),
            accent: "#8b5cf6".into(),
            success: "#62c987".into(),
            warning: "#e0b36a".into(),
            danger: "#e2726a".into(),
            font_family: "system-ui".into(),
        }
    }

    fn render_math(kind: RichKind, source: &str) -> Result<String, String> {
        let iso = RichIsolate::new().expect("isolate should boot");
        iso.render(&WorkerRequest {
            hash: 0,
            kind,
            source: source.to_string(),
            theme: theme(),
            mermaid_theme: None,
        })
    }

    fn render_mermaid(source: &str) -> Result<String, String> {
        padu_mermaid::render_to_svg(source, &padu_mermaid::MermaidTheme::default())
            .map_err(|error| error.to_string())
    }

    fn mermaid_theme() -> padu_mermaid::MermaidTheme {
        padu_mermaid::MermaidTheme::default()
    }

    #[test]
    fn hash_is_stable_and_theme_sensitive() {
        let light = RenderTheme {
            is_dark: false,
            ..theme()
        };
        let a = hash(RichKind::Mermaid, "flowchart LR\nA --> B", &theme());
        let b = hash(RichKind::Mermaid, "flowchart LR\nA --> B", &theme());
        let c = hash(RichKind::Mermaid, "flowchart LR\nA --> B", &light);
        let d = hash(RichKind::Math { display: true }, "E=mc^2", &theme());
        assert_eq!(a, b);
        assert_ne!(a, c);
        assert_ne!(a, d);
    }

    #[test]
    fn math_renders_to_themed_svg() {
        let svg = render_math(RichKind::Math { display: false }, "E = mc^2").expect("render");
        assert!(
            svg.trim_start().starts_with("<svg"),
            "expected svg, got {svg}"
        );
        assert!(
            svg.contains("color=\"#e2e2e2\""),
            "theme color injected: {svg}"
        );
    }

    #[test]
    fn display_math_renders_and_aligns() {
        let iso = RichIsolate::new().unwrap();
        let req = WorkerRequest {
            hash: 0,
            kind: RichKind::Math { display: true },
            source: "\\int_0^\\infty x^2 dx".into(),
            theme: theme(),
            mermaid_theme: None,
        };
        let svg = iso.render(&req).expect("render");
        assert!(svg.trim_start().starts_with("<svg"));
        assert!(svg.contains("color=\"#e2e2e2\""), "theme color injected");
    }

    #[test]
    fn mermaid_renders_to_svg() {
        let svg = render_mermaid(
            "flowchart LR\n  A[Start] --> B{Decision}\n  B -->|yes| C[Continue]\n  B -->|no| D[Stop]\n  C --> A",
        )
        .expect("render");
        assert!(
            svg.trim_start().starts_with("<svg"),
            "expected svg, got {svg}"
        );
        let view_box = svg.find("viewBox=\"").and_then(|start| {
            let rest = &svg[start + "viewBox=\"".len()..];
            rest.find('"').map(|end| rest[..end].to_string())
        });
        assert!(view_box.is_some(), "diagram should carry a viewBox");
        let width = view_box
            .as_deref()
            .and_then(|vb| vb.split(' ').nth(2))
            .and_then(|w| w.parse::<f32>().ok());
        assert!(
            width.is_some_and(|w| (1.0..50000.0).contains(&w)),
            "diagram width should be sane, got {view_box:?}"
        );
        assert!(
            !svg.contains("<foreignObject"),
            "labels must be <text>, not <foreignObject>: resvg cannot raster HTML labels, so they render blank"
        );
        assert!(
            !svg.contains("font-family:undefined") && !svg.contains("font-size:undefined"),
            "the theme font must reach mermaid: {svg}"
        );
    }

    /// The native text measurer derives the viewBox from laid-out geometry. If
    /// child `transform`s were ignored, that box would hug the origin and the
    /// diagram would rasterize blank, so every node's translated origin must
    /// land inside the emitted viewBox.
    #[test]
    fn view_box_covers_every_node() {
        let svg = render_mermaid(
            "flowchart TD\n  A[Christmas] --> B(Go shopping)\n  B --> C{Let me think}\n  C -->|One| D[Laptop]\n  C -->|Two| E[iPhone]\n  C -->|Three| F[fa:fa-car Car]",
        )
        .expect("render");
        let vb = svg.find("viewBox=\"").map(|start| {
            let rest = &svg[start + "viewBox=\"".len()..];
            &rest[..rest.find('"').unwrap_or(0)]
        });
        let vb = vb.expect("diagram should carry a viewBox");
        let coords = vb
            .split_whitespace()
            .filter_map(|part| part.parse::<f32>().ok())
            .collect::<Vec<_>>();
        assert_eq!(coords.len(), 4, "viewBox has four numbers: {vb}");
        let (min_x, min_y, width, height) = (coords[0], coords[1], coords[2], coords[3]);
        assert!(
            width > 400.0,
            "a 6-node TD diagram needs a wide viewBox, got {vb}"
        );
        assert!(
            height > 400.0,
            "a 6-node TD diagram needs a tall viewBox, got {vb}"
        );

        let mut nodes = 0;
        // Node groups carry `transform="translate(x, y)"` followed by a
        // `data-look` attribute in the same tag; edge-label groups share the
        // translate syntax but are nested inside `class="edgeLabel"` groups.
        let node_re = regex::Regex::new(r#"transform="translate\(([^)]*)\)"[^>]*data-look"#)
            .expect("node translate pattern is valid");
        for captures in node_re.captures_iter(&svg) {
            let mut parts = captures[1]
                .split(',')
                .filter_map(|part| part.trim().parse::<f32>().ok());
            let (Some(x), Some(y)) = (parts.next(), parts.next()) else {
                continue;
            };
            nodes += 1;
            assert!(
                x >= min_x && x <= min_x + width && y >= min_y && y <= min_y + height,
                "node origin ({x}, {y}) falls outside viewBox {vb}"
            );
        }
        assert!(
            nodes >= 5,
            "expected every node to be measured, saw {nodes}"
        );
    }

    #[test]
    fn mermaid_error_surfaces_for_invalid_diagrams() {
        let result = render_mermaid("flowchart LR\n  this is not [ valid");
        assert!(
            result.is_err(),
            "invalid diagram should error, got {:?}",
            result
        );
    }

    #[test]
    fn worker_cache_round_trips() {
        let renderer = RichRenderer::spawn();
        let kind = RichKind::Mermaid;
        let source = "flowchart LR\n  A --> B".to_string();
        let theme = theme();
        let key = hash(kind, &source, &theme);

        let first = renderer.ensure(
            key,
            kind,
            source.clone(),
            theme.clone(),
            Some(mermaid_theme()),
        );
        assert!(matches!(first, RenderOutcome::Pending));

        // Poll for the worker to finish (background thread).
        let deadline = Instant::now() + Duration::from_secs(20);
        while !renderer.cache.settled(key) {
            assert!(
                Instant::now() < deadline,
                "worker never completed the render"
            );
            std::thread::sleep(Duration::from_millis(25));
        }
        match renderer.ensure(
            key,
            kind,
            source.clone(),
            theme.clone(),
            Some(mermaid_theme()),
        ) {
            RenderOutcome::Ready(image) => {
                assert_eq!(image.format, ImageFormat::Svg);
                assert!(!image.bytes.is_empty());
            }
            other => panic!("expected a ready image, got {other:?}"),
        }
    }

    #[test]
    fn cache_errors_do_not_thrash() {
        let renderer = RichRenderer::spawn();
        let kind = RichKind::Mermaid;
        let source = "not a diagram [".to_string();
        let theme = theme();
        let key = hash(kind, &source, &theme);
        assert!(matches!(
            renderer.ensure(
                key,
                kind,
                source.clone(),
                theme.clone(),
                Some(mermaid_theme())
            ),
            RenderOutcome::Pending
        ));
        let deadline = Instant::now() + Duration::from_secs(20);
        loop {
            match renderer.ensure(
                key,
                kind,
                source.clone(),
                theme.clone(),
                Some(mermaid_theme()),
            ) {
                RenderOutcome::Pending => {
                    assert!(Instant::now() < deadline);
                    std::thread::sleep(Duration::from_millis(25));
                }
                RenderOutcome::Error(message) => {
                    assert!(!message.is_empty());
                    break;
                }
                RenderOutcome::Ready(_) => panic!("invalid diagram must not succeed"),
            }
        }
    }
}
