/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AgentsRouteImport } from "./routes/agents";
import { Route as AmpRouteImport } from "./routes/amp";
import { Route as AntigravityRouteImport } from "./routes/antigravity";
import { Route as ChangelogRouteImport } from "./routes/changelog";
import { Route as ClaudeCodeRouteImport } from "./routes/claude-code";
import { Route as CodexRouteImport } from "./routes/codex";
import { Route as CursorRouteImport } from "./routes/cursor";
import { Route as DeepseekTuiRouteImport } from "./routes/deepseek-tui";
import { Route as DocsRouteImport } from "./routes/docs";
import { Route as DownloadRouteImport } from "./routes/download";
import { Route as ElphRouteImport } from "./routes/elph";
import { Route as FxRouteImport } from "./routes/fx";
import { Route as GrokRouteImport } from "./routes/grok";
import { Route as KimiRouteImport } from "./routes/kimi";
import { Route as OhmypiRouteImport } from "./routes/ohmypi";
import { Route as OpencodeRouteImport } from "./routes/opencode";
import { Route as PiRouteImport } from "./routes/pi";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as TermsRouteImport } from "./routes/terms";
import { Route as DocsIndexRouteImport } from "./routes/docs/index";
import { Route as DocsSplatRouteImport } from "./routes/docs/$";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AgentsRoute = AgentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const AmpRoute = AmpRouteImport.update({
  id: "/amp",
  path: "/amp",
  getParentRoute: () => rootRouteImport,
} as any);
const AntigravityRoute = AntigravityRouteImport.update({
  id: "/antigravity",
  path: "/antigravity",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogRoute = ChangelogRouteImport.update({
  id: "/changelog",
  path: "/changelog",
  getParentRoute: () => rootRouteImport,
} as any);
const ClaudeCodeRoute = ClaudeCodeRouteImport.update({
  id: "/claude-code",
  path: "/claude-code",
  getParentRoute: () => rootRouteImport,
} as any);
const CodexRoute = CodexRouteImport.update({
  id: "/codex",
  path: "/codex",
  getParentRoute: () => rootRouteImport,
} as any);
const CursorRoute = CursorRouteImport.update({
  id: "/cursor",
  path: "/cursor",
  getParentRoute: () => rootRouteImport,
} as any);
const DeepseekTuiRoute = DeepseekTuiRouteImport.update({
  id: "/deepseek-tui",
  path: "/deepseek-tui",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsRoute = DocsRouteImport.update({
  id: "/docs",
  path: "/docs",
  getParentRoute: () => rootRouteImport,
} as any);
const DownloadRoute = DownloadRouteImport.update({
  id: "/download",
  path: "/download",
  getParentRoute: () => rootRouteImport,
} as any);
const ElphRoute = ElphRouteImport.update({
  id: "/elph",
  path: "/elph",
  getParentRoute: () => rootRouteImport,
} as any);
const FxRoute = FxRouteImport.update({
  id: "/fx",
  path: "/fx",
  getParentRoute: () => rootRouteImport,
} as any);
const GrokRoute = GrokRouteImport.update({
  id: "/grok",
  path: "/grok",
  getParentRoute: () => rootRouteImport,
} as any);
const KimiRoute = KimiRouteImport.update({
  id: "/kimi",
  path: "/kimi",
  getParentRoute: () => rootRouteImport,
} as any);
const OhmypiRoute = OhmypiRouteImport.update({
  id: "/ohmypi",
  path: "/ohmypi",
  getParentRoute: () => rootRouteImport,
} as any);
const OpencodeRoute = OpencodeRouteImport.update({
  id: "/opencode",
  path: "/opencode",
  getParentRoute: () => rootRouteImport,
} as any);
const PiRoute = PiRouteImport.update({
  id: "/pi",
  path: "/pi",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DocsRoute,
} as any);
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => DocsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/agents": typeof AgentsRoute;
  "/amp": typeof AmpRoute;
  "/antigravity": typeof AntigravityRoute;
  "/changelog": typeof ChangelogRoute;
  "/claude-code": typeof ClaudeCodeRoute;
  "/codex": typeof CodexRoute;
  "/cursor": typeof CursorRoute;
  "/deepseek-tui": typeof DeepseekTuiRoute;
  "/docs": typeof DocsRouteWithChildren;
  "/download": typeof DownloadRoute;
  "/elph": typeof ElphRoute;
  "/fx": typeof FxRoute;
  "/grok": typeof GrokRoute;
  "/kimi": typeof KimiRoute;
  "/ohmypi": typeof OhmypiRoute;
  "/opencode": typeof OpencodeRoute;
  "/pi": typeof PiRoute;
  "/privacy": typeof PrivacyRoute;
  "/terms": typeof TermsRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/docs/": typeof DocsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/agents": typeof AgentsRoute;
  "/amp": typeof AmpRoute;
  "/antigravity": typeof AntigravityRoute;
  "/changelog": typeof ChangelogRoute;
  "/claude-code": typeof ClaudeCodeRoute;
  "/codex": typeof CodexRoute;
  "/cursor": typeof CursorRoute;
  "/deepseek-tui": typeof DeepseekTuiRoute;
  "/download": typeof DownloadRoute;
  "/elph": typeof ElphRoute;
  "/fx": typeof FxRoute;
  "/grok": typeof GrokRoute;
  "/kimi": typeof KimiRoute;
  "/ohmypi": typeof OhmypiRoute;
  "/opencode": typeof OpencodeRoute;
  "/pi": typeof PiRoute;
  "/privacy": typeof PrivacyRoute;
  "/terms": typeof TermsRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/docs": typeof DocsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/agents": typeof AgentsRoute;
  "/amp": typeof AmpRoute;
  "/antigravity": typeof AntigravityRoute;
  "/changelog": typeof ChangelogRoute;
  "/claude-code": typeof ClaudeCodeRoute;
  "/codex": typeof CodexRoute;
  "/cursor": typeof CursorRoute;
  "/deepseek-tui": typeof DeepseekTuiRoute;
  "/docs": typeof DocsRouteWithChildren;
  "/download": typeof DownloadRoute;
  "/elph": typeof ElphRoute;
  "/fx": typeof FxRoute;
  "/grok": typeof GrokRoute;
  "/kimi": typeof KimiRoute;
  "/ohmypi": typeof OhmypiRoute;
  "/opencode": typeof OpencodeRoute;
  "/pi": typeof PiRoute;
  "/privacy": typeof PrivacyRoute;
  "/terms": typeof TermsRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/docs/": typeof DocsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/agents"
    | "/amp"
    | "/antigravity"
    | "/changelog"
    | "/claude-code"
    | "/codex"
    | "/cursor"
    | "/deepseek-tui"
    | "/docs"
    | "/download"
    | "/elph"
    | "/fx"
    | "/grok"
    | "/kimi"
    | "/ohmypi"
    | "/opencode"
    | "/pi"
    | "/privacy"
    | "/terms"
    | "/docs/$"
    | "/docs/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/agents"
    | "/amp"
    | "/antigravity"
    | "/changelog"
    | "/claude-code"
    | "/codex"
    | "/cursor"
    | "/deepseek-tui"
    | "/download"
    | "/elph"
    | "/fx"
    | "/grok"
    | "/kimi"
    | "/ohmypi"
    | "/opencode"
    | "/pi"
    | "/privacy"
    | "/terms"
    | "/docs/$"
    | "/docs";
  id:
    | "__root__"
    | "/"
    | "/agents"
    | "/amp"
    | "/antigravity"
    | "/changelog"
    | "/claude-code"
    | "/codex"
    | "/cursor"
    | "/deepseek-tui"
    | "/docs"
    | "/download"
    | "/elph"
    | "/fx"
    | "/grok"
    | "/kimi"
    | "/ohmypi"
    | "/opencode"
    | "/pi"
    | "/privacy"
    | "/terms"
    | "/docs/$"
    | "/docs/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AgentsRoute: typeof AgentsRoute;
  AmpRoute: typeof AmpRoute;
  AntigravityRoute: typeof AntigravityRoute;
  ChangelogRoute: typeof ChangelogRoute;
  ClaudeCodeRoute: typeof ClaudeCodeRoute;
  CodexRoute: typeof CodexRoute;
  CursorRoute: typeof CursorRoute;
  DeepseekTuiRoute: typeof DeepseekTuiRoute;
  DocsRoute: typeof DocsRouteWithChildren;
  DownloadRoute: typeof DownloadRoute;
  ElphRoute: typeof ElphRoute;
  FxRoute: typeof FxRoute;
  GrokRoute: typeof GrokRoute;
  KimiRoute: typeof KimiRoute;
  OhmypiRoute: typeof OhmypiRoute;
  OpencodeRoute: typeof OpencodeRoute;
  PiRoute: typeof PiRoute;
  PrivacyRoute: typeof PrivacyRoute;
  TermsRoute: typeof TermsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents": {
      id: "/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof AgentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/amp": {
      id: "/amp";
      path: "/amp";
      fullPath: "/amp";
      preLoaderRoute: typeof AmpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/antigravity": {
      id: "/antigravity";
      path: "/antigravity";
      fullPath: "/antigravity";
      preLoaderRoute: typeof AntigravityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog": {
      id: "/changelog";
      path: "/changelog";
      fullPath: "/changelog";
      preLoaderRoute: typeof ChangelogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/claude-code": {
      id: "/claude-code";
      path: "/claude-code";
      fullPath: "/claude-code";
      preLoaderRoute: typeof ClaudeCodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/codex": {
      id: "/codex";
      path: "/codex";
      fullPath: "/codex";
      preLoaderRoute: typeof CodexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cursor": {
      id: "/cursor";
      path: "/cursor";
      fullPath: "/cursor";
      preLoaderRoute: typeof CursorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/deepseek-tui": {
      id: "/deepseek-tui";
      path: "/deepseek-tui";
      fullPath: "/deepseek-tui";
      preLoaderRoute: typeof DeepseekTuiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs": {
      id: "/docs";
      path: "/docs";
      fullPath: "/docs";
      preLoaderRoute: typeof DocsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/download": {
      id: "/download";
      path: "/download";
      fullPath: "/download";
      preLoaderRoute: typeof DownloadRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/elph": {
      id: "/elph";
      path: "/elph";
      fullPath: "/elph";
      preLoaderRoute: typeof ElphRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/fx": {
      id: "/fx";
      path: "/fx";
      fullPath: "/fx";
      preLoaderRoute: typeof FxRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/grok": {
      id: "/grok";
      path: "/grok";
      fullPath: "/grok";
      preLoaderRoute: typeof GrokRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/kimi": {
      id: "/kimi";
      path: "/kimi";
      fullPath: "/kimi";
      preLoaderRoute: typeof KimiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ohmypi": {
      id: "/ohmypi";
      path: "/ohmypi";
      fullPath: "/ohmypi";
      preLoaderRoute: typeof OhmypiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/opencode": {
      id: "/opencode";
      path: "/opencode";
      fullPath: "/opencode";
      preLoaderRoute: typeof OpencodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pi": {
      id: "/pi";
      path: "/pi";
      fullPath: "/pi";
      preLoaderRoute: typeof PiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/": {
      id: "/docs/";
      path: "/";
      fullPath: "/docs/";
      preLoaderRoute: typeof DocsIndexRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/$": {
      id: "/docs/$";
      path: "/$";
      fullPath: "/docs/$";
      preLoaderRoute: typeof DocsSplatRouteImport;
      parentRoute: typeof DocsRoute;
    };
  }
}

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute;
  DocsIndexRoute: typeof DocsIndexRoute;
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
};

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AmpRoute: AmpRoute,
  AntigravityRoute: AntigravityRoute,
  ChangelogRoute: ChangelogRoute,
  ClaudeCodeRoute: ClaudeCodeRoute,
  CodexRoute: CodexRoute,
  CursorRoute: CursorRoute,
  DeepseekTuiRoute: DeepseekTuiRoute,
  DocsRoute: DocsRouteWithChildren,
  DownloadRoute: DownloadRoute,
  ElphRoute: ElphRoute,
  FxRoute: FxRoute,
  GrokRoute: GrokRoute,
  KimiRoute: KimiRoute,
  OhmypiRoute: OhmypiRoute,
  OpencodeRoute: OpencodeRoute,
  PiRoute: PiRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
